version: '3.8'

services:
  bot:
    build: agamova/ask_nenaprasno_bot
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - bot_data:/code
    env_file:
      - ./.env

volumes:
  bot_data:
